export const projects = [
  {
    title: 'Porfolio',
    imageUrl: '/assets/portfolio.png',
    modalImageUrl: '/assets/clintboyettModal.png',
    description: 'The Website you\'re on now! This is my portfolio website, I built it in Angular. A couple of years ago. This was actually my first Angular project, although it\'s gone through a lot of updates. In the most recent version I wanted to work on my html/scss skills, so I built as much as I could from scratch.',
    framework: 'Angular',
    frameworkIcon: '/assets/angular.png',
    url: 'https://https://clintboyett.com/home',
    urlToCode: 'https://github.com/clintboyett01/Portfolio',
  },
  {
    title: 'Frontier.io',
    imageUrl: '/assets/frontier.ioPage.jpg',
    modalImageUrl: '/assets/frontier.ioModal.png',
    description: 'My first app. It now has over 10,000 downloads. This was a simple game that was a great first project. I wrote this app in C# using the Unity Game Engine. The game features classic arcade and .io game elements in a competitive map.',
    framework: 'Unity',
    frameworkIcon: '/assets/unity.png',
    url: '',
    urlToCode: '',
  },
  {
    title: 'Pepperwine',
    imageUrl: '/assets/pepperwine.png',
    modalImageUrl: '/assets/pepperwineRVModal.png',
    description: 'Website built in Angular for Pepperwine RV Park. Worked as a freelancer, and customized the website to the customer\'s needs.',
    framework: 'Angular',
    frameworkIcon: '/assets/angular.png',
    url: 'https://pepperwinervpark.org',
    urlToCode: 'https://github.com/clintboyett01/pepperwine',
  },

  {
    title: 'Topotech',
    imageUrl: '/assets/topotech.png',
    modalImageUrl: '/assets/topotechModal.png',
    description: 'Website built in Angular for the 3D Mapping Company: TopoTech. Worked as a freelancer, and customized the website to the customer\'s needs.',
    framework: 'Angular',
    frameworkIcon: '/assets/angular.png',
    url: 'https://topotech.org/home',
    urlToCode: '',
  },
  {
    title: 'DrChatWeb',
    imageUrl: '/assets/DrChatWeb.png',
    modalImageUrl: '/assets/drchatwebModal.png',
    description: 'Website built in Angular for Dr Chat. This is a project that me and a Doctor friend are working on on the side. The website is the Doctors portal, where they can manage their patients, and send them messages. It\'s built in angular, but pending release for a HIPAA compliance legal team.',
    framework: 'Angular',
    frameworkIcon: '/assets/angular.png',
    url: '',
    urlToCode: '',
  },
  {
    title: 'DrChatApp',
    imageUrl: '/assets/DrChatApp.png',
    modalImageUrl: '/assets/drchatappModal.png',
    description: 'App built in Flutter for Dr Chat. This is a project that me and a Doctor friend are working on on the side. The app is the Patient/Aproved Family portal. It\'s built in Flutter, but pending release for a HIPAA compliance legal team.',
    framework: 'Flutter',
    frameworkIcon: '/assets/flutter.png',
    url: '',
    urlToCode: '',
  },
  {
    title: 'Golden Lions',
    imageUrl: '/assets/goldenlions.png',
    modalImageUrl: '/assets/goldenLionsModal.png',
    description: 'App built in Xamarin Forms for Henderson ISD. This app is for the Golden Lions program, that scans and submits the barcode on ID cards for sporting events.',
    framework: 'Xamarin Forms',
    frameworkIcon: '/assets/xamarin.png',
    url: '',
    urlToCode: '',
  },

  {
    title: 'Elliott Electric',
    imageUrl: '/assets/EESPage.jpg',
    modalImageUrl: '/assets/ees1.webp',
    description: 'The Elliott Electric Supply Customer App is an app where customers of Elliott Electric Supply can order and pay for items, change account settings, manage orders and will call pickup, and many other things. This app has sold over 2 million dollars worth of items for EES. I built this app with a team of other developers, and am now lead developer over this app.',
    framework: 'Xamarin Forms',
    frameworkIcon: '/assets/xamarin.png',
    url: 'https://apps.apple.com/us/app/elliott-electric/id473517269',
    urlToCode: '',
  },
  {
    title: '3D Pathfinding',
    imageUrl: '/assets/simNew.png',
    modalImageUrl: '/assets/SimMen.png',
    description: 'This project is a pathfinding algorithm visualizer that offers a wide variety of graphs including three dimensional graphs for different algorithms to transverse. I used poisson disc sampling to create a uniformly random graph that does not have intersecting nodes. The algorithms that this program displays include BFS, DFS, Dijkstra’s Algorithm, and A*. Each can be viewed in real time in a 3D space.',
    framework: 'Unity',
    frameworkIcon: '/assets/unity.png',
    url: 'https://clintboyett.com/Simulation',
    urlToCode: '',
  },
  {
    title: 'DAL Poster',
    imageUrl: '/assets/posterForCard.png',
    modalImageUrl: '/assets/poster.png',
    description: 'Investigated the impact of adjunct drugs on opioid side effects. Analyzed a massive dataset of 135+ million adverse event reports (FDA FAERS) to determine how specific drug combinations affect user outcomes.',
    framework: 'MySQL',
    frameworkIcon: '/assets/mysql.png',
    url: 'https://scholarworks.uttyler.edu/cgi/viewcontent.cgi?filename=0&article=1054&context=lyceum2020&type=additional',
    urlToCode: '',
  }
];